---
title: "Mappeoppgave1"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(readr)
library(data.table)
library(zoo)
```


# Oppgave 1

```{r}
tempratur_df <- fread("http://vortex.nsstc.uah.edu/data/msu/v6.0/tlt/uahncdc_lt_6.0.txt")


tempratur_df <- subset(tempratur_df, select = -c(Land:AUST)) %>% 
  filter(Year !=max(Year),Year != min(Year))

sapply(tempratur_df, class)


tempratur_df$Globe <- as.numeric(tempratur_df$Globe)
tempratur_df$Mo <- as.numeric(tempratur_df$Mo)

sapply(tempratur_df, class)

tempratur_df = tempratur_df %>% 
  mutate(rolltemp = rollmean(Globe, 13,  fill = NA, align ='right'),
         Dato = as.yearmon(paste(tempratur_df$Year, tempratur_df$Mo), "%Y %m"))

tempratur_df$Dato <- as.Date(tempratur_df$Dato)
sapply(tempratur_df, class)


tempratur_df %>% 
  ggplot(aes(x=Dato, y=Globe)) +
  geom_point(aes(x=Dato, y=Globe), colour='blue') + 
  geom_line(aes(x=Dato, y=Globe), colour='blue') +
  geom_line(aes(y=tempratur_df$rolltemp), colour = 'red')+
  geom_hline(yintercept = 0, colour = "black",) +
  labs(title="Globale temperaturer",
       x="År",
       y="Temperatur") +
  scale_x_date(date_breaks = '1 year', date_labels = "%Y") +
  scale_y_continuous(breaks = scales::breaks_pretty(n=20), expand = expansion(add=0.1))+
  theme(axis.text.x = element_text(angle=90, hjust = 1)) 
```

# Oppgave 2

```{r}
Lower_Troposphere <- fread("http://vortex.nsstc.uah.edu/data/msu/v6.0/tlt/uahncdc_lt_6.0.txt")
Mid_Troposphere <- fread("https://www.nsstc.uah.edu/data/msu/v6.0/tmt/uahncdc_mt_6.0.txt")
Tropopause <- fread("https://www.nsstc.uah.edu/data/msu/v6.0/ttp/uahncdc_tp_6.0.txt")
Lower_Stratosphere <- fread("https://www.nsstc.uah.edu/data/msu/v6.0/tls/uahncdc_ls_6.0.txt")

Lower_Troposphere <- subset(Lower_Troposphere, select =c(Year,Mo,NoPol)) %>%
  filter(Year != max(Year), Year != min(Year))%>%
  mutate(Atmosphere = "Lower_Troposphere")

Mid_Troposphere <- subset(Mid_Troposphere, select =c(Year,Mo,NoPol)) %>%
  filter(Year != max(Year), Year != min(Year)) %>%
  mutate(Atmosphere = "Mid_Troposhere")

Tropopause <- subset(Tropopause, select =c(Year,Mo,NoPol)) %>%
  filter(Year != max(Year), Year != min(Year)) %>%
  mutate(Atmosphere = "Tropopause")

Lower_Stratosphere <- subset(Lower_Stratosphere, select =c(Year,Mo,NoPol)) %>%
  mutate(Atmosphere = "Lower_Stratosphere")

Lower_Stratosphere <- Lower_Stratosphere %>%
  mutate_all(as.character)

df <- bind_rows(Lower_Troposphere, Mid_Troposphere,
                    Tropopause, Lower_Stratosphere)

df$NoPol <- as.numeric(df$NoPol)

df <- df %>%
  mutate(tempmean = rollmean(NoPol, k=13, fill=NA, align ='right'),
         Dato = as.yearmon(paste(df$Year, df$Mo), "%Y %m")) 
df$Dato <- as.Date(df$Dato)

ggplot(df,aes(x = Dato, y = NoPol, color = Atmosphere)) +
  geom_path() +
  geom_line(size = 0.5) +
  geom_hline(yintercept = 0) +
  geom_line(aes(y=tempmean, colour='Snitt temp'), size=0.2) +
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  xlab("År") +
  ylab("Tempraturer") + 
  ggtitle("Varierende tempraturer fra 60 grader til 90 grader Nord") +
  theme(plot.title = element_text(hjust = 0.5, size = 13)) +
  theme(axis.title.x = element_text(hjust = 0.5, size = 6)) +
  theme(axis.title.y = element_text(hjust = 0.5, size = 11)) +
  scale_x_date(date_breaks = '1 year', date_labels = "%Y") +
  scale_y_continuous(breaks=scales::breaks_pretty(n=20),
                     expand = expansion(add = 1)) +
  theme(legend.position="bottom")
```

